export const LOGGED_IN = 'LOGGED_IN';
export const CONTACTS = 'CONTACTS';
export const SET_CONTACTS = 'SET_CONTACTS';
export const UPDATE_CONTACTS = 'UPDATE_CONTACTS';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const BATTERY_PERCENTAGE = 'BATTERY_PERCENTAGE';
